# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - richgophishapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_08fcb83d382f4b58b5e89ff64eab12d5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cacca40bb83643bdad226eea4b1f71f7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_08fcb83d382f4b58b5e89ff64eab12d5 }}/matiz22/richgophishclient:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'richgophishapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0806e82aba68445890a214962743fd52 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_08fcb83d382f4b58b5e89ff64eab12d5 }}/matiz22/richgophishclient:${{ github.sha }}'